apiVersion: wac-fiit.github.io/v1alpha1
kind: Project
metadata:
  name: ml-ambulance-wl # napr. <pfx>-ambulance-wl
spec:
  title: Rozvrh pacientov # napr. "Zoznam čakajúcich <pfx>"
  description: Rozvrh pacientov # napr. "Spravuje zoznam pacientov čakajúcich na vyšetrenie v ambulancii"
  authors: Mariia Lytvynova # Zadajte mená autorov
  azureLink: "https://<sub-domain>.azurewebsites.net"
  frontendRepoUrl: "https://github.com/MariiaLytvynova/WAC-projekt"
  backendRepoUrl: "https://github.com/MariiaLytvynova/WAC-ambulance-webapi"
  gitopsRepoUrl: "https://github.com/WAC-ambulance-gitops"