apiVersion: polyfea.github.io/v1alpha1
kind: MicroFrontend
metadata:
  name: ml-ambulance
spec:
  frontendClass: md-shell # default obsiahnutý v základe polyfea md-shell
#  frontendClass: md-shell # default obsiahnutý v základe polyfea md-shell


  service:
    name: ml-ambulance # referencia na službu odkiaľ sa má načítať modul
  modulePath: build/ambulance.esm.js # cesta v rámci služby kde sa modul nachádza

# apiVersion: polyfea.github.io/v1alpha1
# kind: MicroFrontend
# metadata:
#   name: <pfx>-ambulance-ufe
# spec:
#   frontendClass: md-shell # default obsiahnutý v základe polyfea md-shell
#   service:
#     name: <pfx>-ambulance-ufe # referencia na službu odkiaľ sa má načítať modul
#   modulePath: build/ambulance-ufe.esm.js # cesta v rámci služby kde sa modul nachádza